### ISSUE TITLE
Files aren't removed from `eslint-ratchet.json` when all violations are fixed

### ISSUE THREAD

**Issue by TimMoore** [Jmsa/eslint-formatter-ratchet#10]
## Expected Behavior

When I fix all of the warnings and errors in a source code file, I expect it to be removed from `eslint-ratchet.json`.

## Actual Behavior

Files with no issues are not removed from either JSON file.

This seems to be because of a check that filters out changes that aren't in files listed in the results provided to the formatter by ESLint. However, this list only includes files with violations.

## Steps to Reproduce the Problem

1. Start with a project where a file has ESLint warnings
2. Configure the initial `eslint-ratchet.json`
3. Fix all of the warnings in that file
4. Run `eslint -f ratchet` again

## Specifications

- Version: 1.2.0
- Platform: macOS 13.6.7 / Node v20.12.2

**Comment by TimMoore** [comment]
I did more testing and realised that this was only happening when running `next lint` in my project, but it works as expected when running `eslint` directly. So this seems to be a NextJS specific problem.

**Comment by Jmsa** [comment]
Hey @TimMoore thanks for the report. From your description I have two ideas as to what could be happening:
- the file in question isn't actually getting linted (unlikely but always possible)
- next-js is filtering the result set before handing it to the formatter (not sure why it would do this, but you mentioned it only includes violations so seems likely)

In either case if the workaround of running `eslint lint` directly works for you then we can leave it there. If not definitely feel free to reopen this issue (preferably with a small repo that can reproduce the issue 🙏 ).

**Comment by TimMoore** [comment]
Thanks for your response @Jmsa. Next.js is definitely doing some unusual things with the way it invoked ESLint. We've seen other issues with it, and as a consequence we stopped using `next lint` in this project in favour of invoking `eslint` directly. So I'm happy to leave this closed.

**Comment by tterrag1098** [comment]
I'm seeing this same behavior when using ratchet as the output format within [angular's ESLint builder](https://github.com/angular-eslint/angular-eslint/blob/main/packages/builder/README.md), I think this may be addressed by open PR #38 , it seems to me that if a file is now completely missing but was in the previous lint output, it should be flagged as a change and not just emitted to the `-temp` file.

I believe this is the problem code in angular:

https://github.com/angular-eslint/angular-eslint/blob/main/packages/builder/src/lint.impl.ts#L137-L148

and while it's annoying that this isn't configurable, I think the current behavior in the ratchet formatter is also not ideal even if the filtering is intentional. I can imagine a situation in which the input file patterns are changed and files that were previously checked are now skipped, and their lint results would stick around in the output forever, rather than being flagged (correctly) as a ratchet decrease.

**Comment by tterrag1098** [comment]
Just to follow up, I confirmed that the linked code is the issue. Obviously this isn't a real fix, but I think it highlights the problem with simply carrying forward errors from "missing" files.

![Image](https://github.com/user-attachments/assets/0146b7ee-c092-41ce-9f27-58d6699f6f26)
